# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  admin.advert:
        class: DepartmentSite\AdvertBundle\Admin\AdvertAdmin
        arguments: [~, DepartmentSite\AdvertBundle\Entity\Advert, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Advert", label: Advert}
        calls:
              - [ setTranslationDomain, [DepartmentSiteAdvertBundle]]

  admin.news:
        class: DepartmentSite\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "News", label: "News" }
        arguments: [~, DepartmentSite\NewsBundle\Entity\News, ~]
        calls:
             - [ setTranslationDomain, [DepartmentSiteNewsBundle]]

  admin.page:
          class: DepartmentSite\PageBundle\Admin\PageAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Page", label: "Page" }
          arguments: [~, DepartmentSite\PageBundle\Entity\Page, ~]
          calls:
               - [ setTranslationDomain, [DepartmentSitePageBundle]]

  admin.dictionary:
        class: DepartmentSite\DictionaryBundle\Admin\DictionaryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Dictionary", label: "Dictionary" }
        arguments: [~, DepartmentSite\DictionaryBundle\Entity\Dictionary, ~]
        calls:
             - [ setTranslationDomain, [DepartmentSiteNewsBundle]]

  admin.gallery:
          class: DepartmentSite\GalleryBundle\Admin\GalleryAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Gallery", label: "Gallery" }
          arguments: [~, DepartmentSite\GalleryBundle\Entity\Gallery, ~]
          calls:
               - [ setTranslationDomain, [DepartmentSiteGalleryBundle]]
